[project]
name = "tert"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = ["tiktoken", "blobfile"]

[tool.pyright]
venv = ".venv"
venvPath = "."

[tool.ruff]
indent-width = 4
